export type ElderlyProfile = {
  id: string;
  name: string;
  age: number;
  gender: string;
  phone: string;
  medicalCondition: string;
  emergencyContact: string;
  status: "Active" | "Inactive";
  avatar: string;
  dob: string;
  address: string;
  bloodType: string;
  allergies: string;
  doctorName: string;
  relationship: string;
  emergencyPhone: string;
  admissionDate: string;
  notes: string;
};

export type NurseProfile = {
  id: string;
  name: string;
  age: number;
  gender: string;
  phone: string;
  email: string;
  position: string;
  hireDate: string;
  status: "Active" | "On Leave";
  avatar: string;
  assignedElders: number;
  workArea: string;
  nurseStatus: string;
};

export const elderlyData: ElderlyProfile[] = [
  {
    id: "ELD-0001",
    name: "Mary Wilson",
    age: 78,
    gender: "Female",
    phone: "(555) 234-5678",
    medicalCondition: "Hypertension",
    emergencyContact: "James Wilson",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=47",
    dob: "June 12, 1946",
    address: "123 Maple Street, Springfield, IL 62701",
    bloodType: "A+",
    allergies: "Penicillin",
    doctorName: "Dr. Patricia Moore",
    relationship: "Son",
    emergencyPhone: "(555) 987-6543",
    admissionDate: "February 3, 2022",
    notes: "Requires daily blood pressure monitoring. Walks with assistance.",
  },
  {
    id: "ELD-0002",
    name: "Robert Brown",
    age: 82,
    gender: "Male",
    phone: "(555) 345-6789",
    medicalCondition: "Diabetes Type 2",
    emergencyContact: "Patricia Brown",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=12",
    dob: "March 8, 1942",
    address: "456 Oak Avenue, Springfield, IL 62702",
    bloodType: "B+",
    allergies: "Sulfa drugs",
    doctorName: "Dr. James Carter",
    relationship: "Daughter",
    emergencyPhone: "(555) 876-5432",
    admissionDate: "April 15, 2021",
    notes: "Insulin-dependent. Low-sugar diet required.",
  },
  {
    id: "ELD-0003",
    name: "Penney Smith",
    age: 75,
    gender: "Female",
    phone: "(555) 456-7890",
    medicalCondition: "Alzheimer's",
    emergencyContact: "Michael Smith",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=45",
    dob: "September 20, 1949",
    address: "789 Elm Street, Springfield, IL 62703",
    bloodType: "O+",
    allergies: "None",
    doctorName: "Dr. Susan Lee",
    relationship: "Son",
    emergencyPhone: "(555) 765-4321",
    admissionDate: "January 10, 2023",
    notes: "Requires constant supervision. Memory care unit.",
  },
  {
    id: "ELD-0004",
    name: "John Taylor",
    age: 80,
    gender: "Male",
    phone: "(555) 567-8901",
    medicalCondition: "COPD",
    emergencyContact: "Linda Taylor",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=15",
    dob: "July 4, 1944",
    address: "321 Pine Road, Springfield, IL 62704",
    bloodType: "AB+",
    allergies: "Aspirin",
    doctorName: "Dr. Robert Kim",
    relationship: "Wife",
    emergencyPhone: "(555) 654-3210",
    admissionDate: "June 22, 2022",
    notes: "Requires supplemental oxygen. No smoking environment.",
  },
  {
    id: "ELD-0005",
    name: "Elizabeth Davis",
    age: 71,
    gender: "Female",
    phone: "(555) 678-9012",
    medicalCondition: "Arthritis",
    emergencyContact: "Andy Clark",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=44",
    dob: "November 15, 1953",
    address: "654 Cedar Lane, Springfield, IL 62705",
    bloodType: "A-",
    allergies: "Ibuprofen",
    doctorName: "Dr. Emily Chen",
    relationship: "Son",
    emergencyPhone: "(555) 543-2109",
    admissionDate: "August 5, 2022",
    notes: "Physical therapy twice weekly. Mobility aids required.",
  },
  {
    id: "ELD-0006",
    name: "William Davis",
    age: 84,
    gender: "Male",
    phone: "(555) 789-0123",
    medicalCondition: "Heart Disease",
    emergencyContact: "Linda Clark",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=11",
    dob: "February 28, 1940",
    address: "987 Birch Blvd, Springfield, IL 62706",
    bloodType: "O-",
    allergies: "Warfarin sensitivity",
    doctorName: "Dr. Michael Torres",
    relationship: "Daughter",
    emergencyPhone: "(555) 432-1098",
    admissionDate: "March 14, 2021",
    notes: "Cardiac monitoring daily. Low sodium diet required.",
  },
  {
    id: "ELD-0007",
    name: "Barbara Martinez",
    age: 76,
    gender: "Female",
    phone: "(555) 890-1234",
    medicalCondition: "Stroke Recovery",
    emergencyContact: "Carlos Martinez",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=48",
    dob: "August 10, 1948",
    address: "147 Willow Way, Springfield, IL 62707",
    bloodType: "B-",
    allergies: "None",
    doctorName: "Dr. Sarah Johnson",
    relationship: "Son",
    emergencyPhone: "(555) 321-0987",
    admissionDate: "October 1, 2022",
    notes: "Speech therapy ongoing. Left-side weakness.",
  },
  {
    id: "ELD-0008",
    name: "Thomas Anderson",
    age: 79,
    gender: "Male",
    phone: "(555) 901-2345",
    medicalCondition: "Dementia",
    emergencyContact: "Sarah Anderson",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=13",
    dob: "April 5, 1945",
    address: "258 Poplar Street, Springfield, IL 62708",
    bloodType: "A+",
    allergies: "Latex",
    doctorName: "Dr. Daniel Park",
    relationship: "Daughter",
    emergencyPhone: "(555) 210-9876",
    admissionDate: "December 20, 2021",
    notes: "Sundowning episodes in late afternoon. Requires gentle redirection.",
  },
];

export const nurseData: NurseProfile[] = [
  {
    id: "NRS-0001",
    name: "Emily Clark",
    age: 34,
    gender: "Female",
    phone: "(555) 111-2233",
    email: "emily.clark@eldercare.com",
    position: "Senior Nurse",
    hireDate: "March 15, 2020",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=49",
    assignedElders: 8,
    workArea: "Memory Care Unit",
    nurseStatus: "Active",
  },
  {
    id: "NRS-0002",
    name: "James Lee",
    age: 29,
    gender: "Male",
    phone: "(555) 222-3344",
    email: "james.lee@eldercare.com",
    position: "Registered Nurse",
    hireDate: "June 10, 2021",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=53",
    assignedElders: 6,
    workArea: "General Ward",
    nurseStatus: "Active",
  },
  {
    id: "NRS-0003",
    name: "Sophia Martinez",
    age: 38,
    gender: "Female",
    phone: "(555) 333-4455",
    email: "sophia.martinez@eldercare.com",
    position: "Charge Nurse",
    hireDate: "January 5, 2019",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=46",
    assignedElders: 10,
    workArea: "Cardiac Care",
    nurseStatus: "Active",
  },
  {
    id: "NRS-0004",
    name: "Michael Johnson",
    age: 31,
    gender: "Male",
    phone: "(555) 444-5566",
    email: "michael.johnson@eldercare.com",
    position: "Registered Nurse",
    hireDate: "September 20, 2022",
    status: "On Leave",
    avatar: "https://i.pravatar.cc/40?img=14",
    assignedElders: 4,
    workArea: "Rehabilitation",
    nurseStatus: "On Leave",
  },
  {
    id: "NRS-0005",
    name: "Linda Thompson",
    age: 42,
    gender: "Female",
    phone: "(555) 555-6677",
    email: "linda.thompson@eldercare.com",
    position: "Nurse Practitioner",
    hireDate: "April 12, 2018",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=43",
    assignedElders: 12,
    workArea: "Palliative Care",
    nurseStatus: "Active",
  },
  {
    id: "NRS-0006",
    name: "David Wilson",
    age: 27,
    gender: "Male",
    phone: "(555) 666-7788",
    email: "david.wilson@eldercare.com",
    position: "LPN",
    hireDate: "February 28, 2023",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=52",
    assignedElders: 5,
    workArea: "General Ward",
    nurseStatus: "Active",
  },
  {
    id: "NRS-0007",
    name: "Amanda Garcia",
    age: 35,
    gender: "Female",
    phone: "(555) 777-8899",
    email: "amanda.garcia@eldercare.com",
    position: "Registered Nurse",
    hireDate: "July 1, 2020",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=42",
    assignedElders: 7,
    workArea: "Memory Care Unit",
    nurseStatus: "Active",
  },
];
